### ISSUE TITLE
Merge into strapi's main s3 provider?

### ISSUE THREAD

**Issue by aguynamedjoetoo** [stephent/strapi-provider-upload-aws-s3-cdn#1]
First off, thanks for this provider! Have you attempted to submit a PR to merge this into the standard strapi provider? I'd love to take advantage of this while also keeping up to date with any changes to the strapi s3 provider at the same time. I'd be happy to make the PR myself, but didn't wanna take credit for your work!

**Comment by stephent** [comment]
Hi @jinglejengel - I hadn't thought to do that. Probably a good idea, but it looks like right now is probably not the best time: https://forum.strapi.io/t/notice-community-pull-request-change-freeze/9124

**Comment by aguynamedjoetoo** [comment]
Shoot, good catch. I'll patiently wait then ;)

**Comment by SalahAdDin** [comment]
Well, there is a new Strapi version, so....

**Comment by stephent** [comment]
> Well, there is a new Strapi version, so....

Indeed. But there's no migration guide from v3.x to 4.0 as yet. 

Feel free to submit a PR if you're in a hurry, but all my projects are on v3.x. I'll look at updating this when I migrate them to v4 (which will have to wait for the migration guide...)

**Comment by AzaxSyndrom** [comment]
Hello ! 

so this plugin doesn't work anymore on Strapi V4 ? Do you have any news when it could be done ?

Thanks !

**Comment by SalahAdDin** [comment]
> Hello !
> 
> so this plugin doesn't work anymore on Strapi V4 ? Do you have any news when it could be done ?
> 
> Thanks !

I don't think this plugin is being maintained anymore.

**Comment by stephent** [comment]
> I don't think this plugin is being maintained anymore.

Folks - right now I don't have any Strapi 4 project configured. Strapi made the rather dumb decision, in my view, not to prioritize a migration guide from v3 to v4. It's apparently due this month. As soon as I have that, then I'll get back to this.

That all said, this project has maybe 2-3 lines that are different from the official S3 upload provider, so it's almost certainly not terribly hard to recreate what you need from that.

**Comment by AzaxSyndrom** [comment]
Hello, 

i asked the question because i thought they released this migration guide already (updated January 2022)
https://strapi.io/blog/v4-plugin-migration-guide

But truth is,  i just find here https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html they said it would be in March 2022. MyBad. 

I still don't understand why they couldn't update their official plugin with private bucket and CloudFront access.

**Comment by fthues** [comment]
No, the _plugin_ migration guide is there. What is still missing is the guide for migrating an existing Strapi v3 _installation_ to a v4 one.

**Comment by colearendt** [comment]
Just a note that the installation migration guide is present now:

https://docs.strapi.io/developer-docs/latest/update-migration-guides/migration-guides.html#v3-to-v4-migration-guides

There are also some data migration scripts that worked pretty well for me:

https://github.com/strapi/migration-scripts

**Comment by stephent** [comment]
Just updated this package to v4.0.0 with assistance from @MattieBelt 🙏
